web/router.ex
defmodule IssueReporter.Router do
  use IssueReporter.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug IssueReporter.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IssueReporter do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/set-lang/:lang_code/", LocaleController, :set_lang
  end

  # Other scopes may use custom stacks.
  scope "/api", IssueReporter do
    pipe_through :api

    get "/issues/", IssueController, :index
    post "/issues/", IssueController, :create
    get "/issues/:id/", IssueController, :show
    put "/issues/:id/", IssueController, :update
    delete "/issues/:id/", IssueController, :delete
  end
end

lib/issue_reporter/endpoint.ex
defmodule IssueReporter.Endpoint do
  use Phoenix.Endpoint, otp_app: :issue_reporter

  socket "/socket", IssueReporter.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :issue_reporter, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_issue_reporter_key",
    signing_salt: "JLoiNPAF"

  plug IssueReporter.Router
end

lib/issue_reporter/repo.ex
defmodule IssueReporter.Repo do
  use Ecto.Repo, otp_app: :issue_reporter
end

web/models/issue.ex
defmodule IssueReporter.Issue do
  use IssueReporter.Web, :model

  schema "issues" do
    field :type, :string
    field :latitude, :float
    field :longitude, :float
    field :fixed, :boolean, default: false
    field :message, :string

    timestamps
  end

  @required_fields ~w(type latitude longitude fixed)
  @optional_fields ~w(message)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def unfixed(query) do
    from i in query,
    where: i.fixed == false
  end

  def fixed(query) do
    from i in query,
    where: i.fixed == true
  end
end

web/controllers/issue_controller.ex
defmodule IssueReporter.IssueController do
  use IssueReporter.Web, :controller

  plug :scrub_params, "issue" when action in [:create, :update]

  alias IssueReporter.Issue

  def index(conn, params) do
    issues = Issue
    # TODO: find a better way to make this query
    case params["fixed"] do
      "true" ->
        issues = issues |> Issue.fixed
      "false" ->
        issues = issues |> Issue.unfixed
      _ -> nil
    end
    issues = issues |> Repo.all
    render(conn, "index.json", issues: issues)
  end

  def create(conn, %{"issue" => issue_params}) do
    changeset = Issue.changeset(%Issue{}, issue_params)

    case Repo.insert(changeset) do
      {:ok, issue} ->
        conn
        |> put_status(:created)
        |> put_resp_header("location", issue_path(conn, :show, issue))
        |> render("show.json", issue: issue)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(IssueReporter.ChangesetView, "error.json", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    issue = Repo.get!(Issue, id)
    render(conn, "show.json", issue: issue)
  end

  def update(conn, %{"id" => id, "issue" => issue_params}) do
    issue = Repo.get!(Issue, id)
    changeset = Issue.changeset(issue, issue_params)

    case Repo.update(changeset) do
      {:ok, issue} ->
        render(conn, "show.json", issue: issue)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(IssueReporter.ChangesetView, "error.json", changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    issue = Repo.get!(Issue, id)
    Repo.delete!(issue)
    send_resp(conn, :no_content, "")
  end
end

web/controllers/locale_controller.ex
defmodule IssueReporter.LocaleController do
  use IssueReporter.Web, :controller

  def set_lang(conn, %{"lang_code" => lang_code}) do
    conn = put_session(conn, :lang_code, lang_code)
    redirect conn, to: get_url(conn)
  end

  defp get_url(conn) do
    case get_req_header(conn, "referer") do
      [referer] when is_binary(referer) ->
        [host] = get_req_header(conn, "host")
        referer |> String.replace("#{conn.scheme}://#{host}", "")
      _ ->
        "/"
    end
  end
end

web/controllers/page_controller.ex
defmodule IssueReporter.PageController do
  use IssueReporter.Web, :controller
  import IssueReporter.Gettext

  def index(conn, _params) do
    issue_types = [
      %{key: "broken semaphore", value: gettext("Broken semaphore")},
      %{key: "broken lamp post", value: gettext("Broken lamp post")},
    ]
    render conn, "index.html",  issue_types: issue_types
  end
end

web/views/changeset_view.ex
defmodule IssueReporter.ChangesetView do
  use IssueReporter.Web, :view

  def translate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
  end

  def render("error.json", %{changeset: changeset}) do
    # When encoded, the changeset returns its errors
    # as a JSON object. So we just pass it forward.
    %{errors: translate_errors(changeset)}
  end
end

web/views/error_view.ex
defmodule IssueReporter.ErrorView do
  use IssueReporter.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/issue_view.ex
defmodule IssueReporter.IssueView do
  use IssueReporter.Web, :view

  def render("index.json", %{issues: issues}) do
    %{data: render_many(issues, IssueReporter.IssueView, "issue.json")}
  end

  def render("show.json", %{issue: issue}) do
    %{data: render_one(issue, IssueReporter.IssueView, "issue.json")}
  end

  def render("issue.json", %{issue: issue}) do
    %{
      id: issue.id,
      type: issue.type,
      latitude: issue.latitude,
      longitude: issue.longitude,
      fixed: issue.fixed,
      message: issue.message
    }
  end
end

web/views/layout_view.ex
defmodule IssueReporter.LayoutView do
  use IssueReporter.Web, :view
end

web/views/page_view.ex
defmodule IssueReporter.PageView do
  use IssueReporter.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Yo reporto</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
    <link rel="stylesheet" href="//aratcliffe.github.io/Leaflet.contextmenu/dist/leaflet.contextmenu.css" />
    <link href='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v0.0.2/leaflet.fullscreen.css' rel='stylesheet' />
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <h1>Yo reporto</h1>
        <div class="btn-group pull-right">
          <a class="btn btn-default" href="<%= locale_path(@conn, :set_lang, "es") %>">
            es
          </a>
          <a class="btn btn-default" href="<%= locale_path(@conn, :set_lang, "en") %>">
            en
          </a>
        </div>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <script src="//cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
    <script src="//aratcliffe.github.io/Leaflet.contextmenu/dist/leaflet.contextmenu.js"></script>
    <script src='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v0.0.2/Leaflet.fullscreen.min.js'></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div style="margin-bottom: 10px">
  <button class="btn btn-default" id="btn-enable-geolocation">
    <%= gettext "Set current location" %>
  </button>
  <button class="btn btn-default" id="btn-load-all-issues">
    <%= gettext "Load all issues" %>
  </button>
  <button class="btn btn-default" id="btn-load-fixed">
    <%= gettext "Load fixed issues" %>
  </button>
  <button class="btn btn-default" id="btn-load-unfixed">
    <%= gettext "Load unfixed issues" %>
  </button>
  <p>
    <%= gettext("Right click or tap and hold in the desired position for report an issue") %>
  </p>
</div>
<div id="map" style="width: 100%; height: 500px"></div>

<div class="modal fade" id="issue-modal" tabindex="-1" role="dialog" aria-labelledby="issue-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="exampleModalLabel"><%= gettext "New issue" %></h4>
      </div>
      <div class="modal-body">
        <form id="issue-form">
          <input type="hidden" name="latitude"/>
          <input type="hidden" name="longitude"/>
          <div class="form-group">
            <label for="type" class="control-label"><%= gettext "Type" %>:</label>
            <select id="type" name="type" class="form-control">
            <%= for type <- @issue_types do %>
              <option value="<%= type.key %>"><%= type.value %></option>
            <% end %>
            </select>
          </div>
          <div class="form-group">
            <label for="message" class="control-label"><%= gettext "Message" %>:</label>
            <textarea class="form-control" id="message" name="message"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= gettext "Close" %></button>
        <button type="button" class="btn btn-primary" id="btn-add-issue"><%= gettext "Send issue" %></button>
      </div>
    </div>
  </div>
</div>